// Base-type decoder table, ported from demoinfocs-golang (MIT),
// sendtables/sendtablescs2/field_decoder.go (fieldTypeDecoders). See NOTICE.

#include "cyka/demo/ent/decoder_types.hpp"

namespace cyka::demo::ent {

const std::unordered_map<std::string_view, DecOp>& typeDecoders() {
    static const std::unordered_map<std::string_view, DecOp> MAP{
        {"bool",                              DecOp::BOOL        },
        {"int8",                              DecOp::SIGNED      },
        {"int16",                             DecOp::SIGNED      },
        {"int32",                             DecOp::SIGNED      },
        {"uint8",                             DecOp::UNSIGNED    },
        {"uint16",                            DecOp::UNSIGNED    },
        {"uint32",                            DecOp::UNSIGNED    },
        {"char",                              DecOp::STRING      },
        {"CUtlString",                        DecOp::STRING      },
        {"CUtlSymbolLarge",                   DecOp::STRING      },
        {"CGlobalSymbol",                     DecOp::STRING      },
        {"GameTime_t",                        DecOp::NO_SCALE    },
        {"CHandle",                           DecOp::UNSIGNED    },
        {"Color",                             DecOp::UNSIGNED    },
        {"CUtlStringToken",                   DecOp::UNSIGNED    },
        {"EHandle",                           DecOp::UNSIGNED    },
        {"CEntityHandle",                     DecOp::UNSIGNED    },
        {"CGameSceneNodeHandle",              DecOp::UNSIGNED    },
        {"CUtlBinaryBlock",                   DecOp::BINARY_BLOCK},
        {"HSequence",                         DecOp::SIGNED      },
        {"AttachmentHandle_t",                DecOp::UNSIGNED    },
        {"CEntityIndex",                      DecOp::SIGNED      },
        {"MoveCollide_t",                     DecOp::UNSIGNED    },
        {"MoveType_t",                        DecOp::UNSIGNED    },
        {"RenderMode_t",                      DecOp::UNSIGNED    },
        {"RenderFx_t",                        DecOp::UNSIGNED    },
        {"SolidType_t",                       DecOp::UNSIGNED    },
        {"SurroundingBoundsType_t",           DecOp::UNSIGNED    },
        {"ModelConfigHandle_t",               DecOp::UNSIGNED    },
        {"NPC_STATE",                         DecOp::SIGNED      },
        {"StanceType_t",                      DecOp::SIGNED      },
        {"WeaponState_t",                     DecOp::UNSIGNED    },
        {"DoorState_t",                       DecOp::UNSIGNED    },
        {"RagdollBlendDirection",             DecOp::SIGNED      },
        {"BeamType_t",                        DecOp::SIGNED      },
        {"BeamClipStyle_t",                   DecOp::UNSIGNED    },
        {"EntityDisolveType_t",               DecOp::SIGNED      },
        {"ValueRemapperInputType_t",          DecOp::UNSIGNED    },
        {"ValueRemapperOutputType_t",         DecOp::UNSIGNED    },
        {"ValueRemapperHapticsType_t",        DecOp::UNSIGNED    },
        {"ValueRemapperMomentumType_t",       DecOp::UNSIGNED    },
        {"ValueRemapperRatchetType_t",        DecOp::UNSIGNED    },
        {"PointWorldTextJustifyHorizontal_t", DecOp::UNSIGNED    },
        {"PointWorldTextJustifyVertical_t",   DecOp::UNSIGNED    },
        {"PointWorldTextReorientMode_t",      DecOp::UNSIGNED    },
        {"PoseController_FModType_t",         DecOp::UNSIGNED    },
        {"PrecipitationType_t",               DecOp::SIGNED      },
        {"ShardSolid_t",                      DecOp::UNSIGNED    },
        {"ShatterPanelMode",                  DecOp::UNSIGNED    },
        {"gender_t",                          DecOp::UNSIGNED    },
        {"item_definition_index_t",           DecOp::UNSIGNED    },
        {"itemid_t",                          DecOp::UNSIGNED    },
        {"style_index_t",                     DecOp::UNSIGNED    },
        {"attributeprovidertypes_t",          DecOp::UNSIGNED    },
        {"DamageOptions_t",                   DecOp::UNSIGNED    },
        {"ScreenEffectType_t",                DecOp::UNSIGNED    },
        {"MaterialModifyMode_t",              DecOp::UNSIGNED    },
        {"AmmoIndex_t",                       DecOp::SIGNED      },
        {"TakeDamageFlags_t",                 DecOp::SIGNED      },
        {"CSWeaponMode",                      DecOp::UNSIGNED    },
        {"ESurvivalSpawnTileState",           DecOp::UNSIGNED    },
        {"SpawnStage_t",                      DecOp::UNSIGNED    },
        {"ESurvivalGameRuleDecision_t",       DecOp::UNSIGNED    },
        {"RelativeDamagedDirection_t",        DecOp::UNSIGNED    },
        {"CSPlayerState",                     DecOp::UNSIGNED    },
        {"MedalRank_t",                       DecOp::UNSIGNED    },
        {"CSPlayerBlockingUseAction_t",       DecOp::UNSIGNED    },
        {"MoveMountingAmount_t",              DecOp::UNSIGNED    },
        {"QuestProgress::Reason",             DecOp::UNSIGNED    },
        {"tablet_skin_state_t",               DecOp::UNSIGNED    },
        {"CBodyComponent",                    DecOp::COMPONENT   },
        {"CPhysicsComponent",                 DecOp::COMPONENT   },
        {"CLightComponent",                   DecOp::COMPONENT   },
        {"CRenderComponent",                  DecOp::COMPONENT   },
        {"ResourceId_t",                      DecOp::UNSIGNED64  },
    };
    return MAP;
}

} // namespace cyka::demo::ent
