// Base-type decoder table, ported from demoinfocs-golang (MIT),
// sendtables/sendtablescs2/field_decoder.go (fieldTypeDecoders). See NOTICE.

#include "cyka/demo/ent/decoder_types.hpp"

namespace cyka::demo::ent {

const std::unordered_map<std::string_view, DecOp>& type_decoders() {
    static const std::unordered_map<std::string_view, DecOp> kMap{
        {"bool", DecOp::Bool},
        {"int8", DecOp::Signed},
        {"int16", DecOp::Signed},
        {"int32", DecOp::Signed},
        {"uint8", DecOp::Unsigned},
        {"uint16", DecOp::Unsigned},
        {"uint32", DecOp::Unsigned},
        {"char", DecOp::String},
        {"CUtlString", DecOp::String},
        {"CUtlSymbolLarge", DecOp::String},
        {"CGlobalSymbol", DecOp::String},
        {"GameTime_t", DecOp::NoScale},
        {"CHandle", DecOp::Unsigned},
        {"Color", DecOp::Unsigned},
        {"CUtlStringToken", DecOp::Unsigned},
        {"EHandle", DecOp::Unsigned},
        {"CEntityHandle", DecOp::Unsigned},
        {"CGameSceneNodeHandle", DecOp::Unsigned},
        {"CUtlBinaryBlock", DecOp::BinaryBlock},
        {"HSequence", DecOp::Signed},
        {"AttachmentHandle_t", DecOp::Unsigned},
        {"CEntityIndex", DecOp::Signed},
        {"MoveCollide_t", DecOp::Unsigned},
        {"MoveType_t", DecOp::Unsigned},
        {"RenderMode_t", DecOp::Unsigned},
        {"RenderFx_t", DecOp::Unsigned},
        {"SolidType_t", DecOp::Unsigned},
        {"SurroundingBoundsType_t", DecOp::Unsigned},
        {"ModelConfigHandle_t", DecOp::Unsigned},
        {"NPC_STATE", DecOp::Signed},
        {"StanceType_t", DecOp::Signed},
        {"WeaponState_t", DecOp::Unsigned},
        {"DoorState_t", DecOp::Unsigned},
        {"RagdollBlendDirection", DecOp::Signed},
        {"BeamType_t", DecOp::Signed},
        {"BeamClipStyle_t", DecOp::Unsigned},
        {"EntityDisolveType_t", DecOp::Signed},
        {"ValueRemapperInputType_t", DecOp::Unsigned},
        {"ValueRemapperOutputType_t", DecOp::Unsigned},
        {"ValueRemapperHapticsType_t", DecOp::Unsigned},
        {"ValueRemapperMomentumType_t", DecOp::Unsigned},
        {"ValueRemapperRatchetType_t", DecOp::Unsigned},
        {"PointWorldTextJustifyHorizontal_t", DecOp::Unsigned},
        {"PointWorldTextJustifyVertical_t", DecOp::Unsigned},
        {"PointWorldTextReorientMode_t", DecOp::Unsigned},
        {"PoseController_FModType_t", DecOp::Unsigned},
        {"PrecipitationType_t", DecOp::Signed},
        {"ShardSolid_t", DecOp::Unsigned},
        {"ShatterPanelMode", DecOp::Unsigned},
        {"gender_t", DecOp::Unsigned},
        {"item_definition_index_t", DecOp::Unsigned},
        {"itemid_t", DecOp::Unsigned},
        {"style_index_t", DecOp::Unsigned},
        {"attributeprovidertypes_t", DecOp::Unsigned},
        {"DamageOptions_t", DecOp::Unsigned},
        {"ScreenEffectType_t", DecOp::Unsigned},
        {"MaterialModifyMode_t", DecOp::Unsigned},
        {"AmmoIndex_t", DecOp::Signed},
        {"TakeDamageFlags_t", DecOp::Signed},
        {"CSWeaponMode", DecOp::Unsigned},
        {"ESurvivalSpawnTileState", DecOp::Unsigned},
        {"SpawnStage_t", DecOp::Unsigned},
        {"ESurvivalGameRuleDecision_t", DecOp::Unsigned},
        {"RelativeDamagedDirection_t", DecOp::Unsigned},
        {"CSPlayerState", DecOp::Unsigned},
        {"MedalRank_t", DecOp::Unsigned},
        {"CSPlayerBlockingUseAction_t", DecOp::Unsigned},
        {"MoveMountingAmount_t", DecOp::Unsigned},
        {"QuestProgress::Reason", DecOp::Unsigned},
        {"tablet_skin_state_t", DecOp::Unsigned},
        {"CBodyComponent", DecOp::Component},
        {"CPhysicsComponent", DecOp::Component},
        {"CLightComponent", DecOp::Component},
        {"CRenderComponent", DecOp::Component},
        {"ResourceId_t", DecOp::Unsigned64},
    };
    return kMap;
}

} // namespace cyka::demo::ent
