#!/usr/bin/env python3
"""Emit portable constexpr byte-array includes from generated/*.bin (no #embed)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "src" / "csdata"
GEN = ROOT / "generated"


def emit_inc(stem: str, data: bytes) -> None:
    name = stem.upper().replace(".", "_") + "_RAW"
    lines = [
        "// Auto-generated by scripts/generate_spray_incs.py — do not edit.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "",
        f"inline constexpr std::array<unsigned char, {len(data)}> {name}{{",
    ]
    row: list[str] = []
    for idx, byte in enumerate(data):
        row.append(f"0x{byte:02x}")
        if len(row) == 16 or idx + 1 == len(data):
            comma = "," if idx + 1 != len(data) else ""
            lines.append("    " + ", ".join(row) + comma)
            row = []
    lines.append("};")
    lines.append("")
    (GEN / f"{stem}.inc").write_text("\n".join(lines))
    print(f"{stem}.bin -> {stem}.inc ({len(data)} bytes, {name})")


def main() -> None:
    manifest = json.loads((GEN / "manifest.json").read_text())
    for entry in manifest.values():
        stem = Path(str(entry["file"])).stem
        data = (GEN / entry["file"]).read_bytes()
        expected = int(entry["count"]) * 2 * 8
        if len(data) != expected:
            raise SystemExit(f"{entry['file']}: size {len(data)} != expected {expected}")
        emit_inc(stem, data)


if __name__ == "__main__":
    main()
